### Get all results locally
GET http://localhost:7071/api/results
Accept: application/json


### Get one result locally
# Replace RESULT_ID with an actual ID returned by the first request
GET http://localhost:7071/api/results/RESULT_ID
Accept: application/json


### Get all results from Azure
GET https://ilyas-image-analyzer-735689.azurewebsites.net/api/results
Accept: application/json


### Get one result from Azure
# Replace RESULT_ID with an actual stored result ID
GET https://ilyas-image-analyzer-735689.azurewebsites.net/api/results/RESULT_ID
Accept: application/json
